### ISSUE TITLE
Update fix_timestamp_bug(file) to reflect new h5 file format

### ISSUE THREAD

**Issue by IsabelLipartito** [MazinLab/MKIDPipeline#14]
I'm testing out the fix_timestamp_bug() code in bin2hdf and it chokes on this line: photonTable = hfile.get_node('/Photons/' + str(resID))

I think we changed the h5 files so this structure doesn't exist anymore, there's only '/Photons/PhotonTable/'
  I rewrote the code to grab the entire PhotonTable and push it through _correct_timestamps(timestamps).
Will that work?  Previously, the code was iterating through each RESID, grabbing the PhotonTable, and pushing it through _correct_timestamps(timestamps) for each [xpix, ypix]

**Comment by neelay893** [comment]
Pushing the entire table through _correct_timestamps won't work because the large photon table is sorted primarily by resID, not time. What was wrong w/ the previous method (iterating through each resID)?

**Comment by IsabelLipartito** [comment]
Closing this issue because fix_timestamp_bug(file) is now updated to reflect new h5 file format.  The remaining issue is now with bin2hdf.c
