### ISSUE TITLE
Add functionality to getPixelCountImage in photontable to ID dead pixels

### ISSUE THREAD

**Issue by IsabelLipartito** [MazinLab/MKIDPipeline#18]
getPixelCountImage in photontable currently has no way of discriminating dead pixels (counts=0) from pixels that are registering zero counts (for an actual astrophysical reason).  Dead pixels need to be set to np.NaN

**Comment by neelay893** [comment]
getPixelCountImage should be setting pixels to nan if they don't meet the criteria specified in flagToUse (default is 0, which means all cals (that have happened so far) have passed). Is this not working/not what you want?

**Comment by IsabelLipartito** [comment]
No, dead pixels are returned as '0', not np.nans
