### ISSUE TITLE
pipeline will stall during the creation of h5 files

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDPipeline#23]
Sometimes the pipeline will stall when making h5 files (with no printed log messages), but then if you stop the script and run it again it will finish with no issues. Not sure why this is happening/if its a known problem with memory or else if its a bug

**Comment by baileyji** [comment]
Does this happen in multiprocessing mode only, or with a consistent dataset/time-range? Also can you identify which log messages occur before the apparent hang and which one should come next?
