### ISSUE TITLE
bug in line 105 of drizzler.py

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDPipeline#28]
In the creation of the DitherDescription object, 'lookup_coordinates' is trying to be called on an MKIDObsevation object when 'lookup_coordinates' is an attribute of the MKIDTimerange object 
  
File "/home/steigersg/src/mkidpipeline/mkidpipeline/imaging/drizzler.py", line 802, in form
    ditherdesc = DitherDescription(dither, target=dither.name, rotation_center=rotation_center)
  File "/home/steigersg/src/mkidpipeline/mkidpipeline/imaging/drizzler.py", line 105, in __init__
    self.coords = dither.obs[0].lookup_coordinates(queryname=target)
AttributeError: 'MKIDObservation' object has no attribute 'lookup_coordinates'

**Comment by baileyji** [comment]
Sarah wasn't this fixed?
