### ISSUE TITLE
bug in line 823 of photontable.py

### ISSUE THREAD

**Issue by IsabelLipartito** [MazinLab/MKIDPipeline#32]
line 823:        for k, v in self.metadata().items():
AttributeError: 'function' object has no attribute 'items'

**Comment by steigersg** [comment]
I'm getting an error in the same spot its 

  File "/opt/anaconda3/envs/pipeline/lib/python3.6/site-packages/astropy/io/fits/card.py", line 311, in value
    raise ValueError('Illegal value: {!r}.'.format(value))
ValueError: Illegal value: ['Star with a known Hot Jupiter'].

so it seems like I have metadata its just not liking how I have the comment formatted?

**Comment by baileyji** [comment]
This looks interesting, lets give the data.yml a look tomorrow.

**Comment by IsabelLipartito** [comment]
I was not attaching the metadata correctly.  
But now it gives me this error:
    'ASCII or non-printable characters.'.format(value))
ValueError: FITS header values must contain standard printable ASCII characters; 'flatcal_850 nm (1547376554-1547376654)\n 950 nm (1547376662-1547376762)\n 1100 nm (1547376788-1547376888)\n 1250 nm (1547376895-1547376995)\n 1375 nm (1547377000-1547377100).h5' contains characters not representable in ASCII or non-printable characters.

It is not able to attach the name of the flatcal file

**Comment by baileyji** [comment]
The proper fix for this will be to migrate to a flat cal file name more akin to the wavecals and ensure the flatcal stores all relevant info in itself as to what went into it.

**Comment by baileyji** [comment]
> I was not attaching the metadata correctly.
> But now it gives me this error:
> 'ASCII or non-printable characters.'.format(value))
> ValueError: FITS header values must contain standard printable ASCII characters; 'flatcal_850 nm (1547376554-1547376654)\n 950 nm (1547376662-1547376762)\n 1100 nm (1547376788-1547376888)\n 1250 nm (1547376895-1547376995)\n 1375 nm (1547377000-1547377100).h5' contains characters not representable in ASCII or non-printable characters.
> 
> It is not able to attach the name of the flatcal file

Please create a separate bug to track this.
