### ISSUE TITLE
Flatcal filename unable to be attached

### ISSUE THREAD

**Issue by IsabelLipartito** [MazinLab/MKIDPipeline#33]
'ASCII or non-printable characters.'.format(value))
ValueError: FITS header values must contain standard printable ASCII characters; 'flatcal_850 nm (1547376554-1547376654)\n 950 nm (1547376662-1547376762)\n 1100 nm (1547376788-1547376888)\n 1250 nm (1547376895-1547376995)\n 1375 nm (1547377000-1547377100).h5' contains characters not representable in ASCII or non-printable characters.

**Comment by IsabelLipartito** [comment]
- !wc
  name: wavecal_01122019
  data:
    - !ob
      name: 850 nm
      start: 1547376554
      duration: 100  
      ndensity: open
      lamp: 100
    - !ob
      name: 950 nm
      start: 1547376662
      duration: 100
      ndensity: open
      lamp: 100
    - !ob
      name: 1100 nm
      start: 1547376788
      duration: 100
      ndensity: 1.0
      lamp: 40
    - !ob
      name: 1250 nm
      start: 1547376895
      duration: 100
      ndensity: 1.0
      lamp: 40
    - !ob
      name: 1375 nm
      start: 1547377000
      duration: 100      
      ndensity: 1.0
      lamp: 40

- !fc
  name: flatcal_01122019
  wavecal: wavecal_01122019

- !sob
  name: HD37021
  start: 1547374444
  duration: 100
  ra: 05:35:16.112
  dec: -05:23:06.89
  airmass: 1.261
  az: 48.7
  el: 52.5
  ha: 1.46
  parallactic: 45.2
  target: HD37021
  filter: Y Band, Filter Open
  observatory: subaru
  utc: 20190113101404
  instrument: mec
  dither_pos: 5
  wavecal: wavecal_01122019
  flatcal: flatcal_01122019
  wcscal: wcscal_01122019

- !wcscal
  name: wcscal_01122019
  platescale: 0.1
  dither_ref: [0.23, -0.38]
  dither_home: [107, 61]
  device_orientation: -48

**Comment by IsabelLipartito** [comment]
I found this error when I deleted all KEYWORD 

> comments

.  So if you have any comments in your yml file, you will not see this error, you will see issue #34 instead

**Comment by IsabelLipartito** [comment]
`Traceback (most recent call last):
  File "runpipeline_HD984.py", line 80, in <module>
    generate_outputs(outputs)
  File "runpipeline_HD984.py", line 62, in generate_outputs
    applyTPFWeight=o.enable_noise, countRate=True)
  File "/home/isabel/src/mkidpipeline/mkidpipeline/hdf/photontable.py", line 824, in getFits
    header[k] = v
  File "/opt/anaconda3/envs/pipeline/lib/python3.6/site-packages/astropy/io/fits/header.py", line 189, in __setitem__
    self._update((key, value, comment))
  File "/opt/anaconda3/envs/pipeline/lib/python3.6/site-packages/astropy/io/fits/header.py", line 1609, in _update
    self.append(card)
  File "/opt/anaconda3/envs/pipeline/lib/python3.6/site-packages/astropy/io/fits/header.py", line 1141, in append
    card = Card(*card)
  File "/opt/anaconda3/envs/pipeline/lib/python3.6/site-packages/astropy/io/fits/card.py", line 191, in __init__
    self.value = value
  File "/opt/anaconda3/envs/pipeline/lib/python3.6/site-packages/astropy/io/fits/card.py", line 323, in value
    'ASCII or non-printable characters.'.format(value))
ValueError: FITS header values must contain standard printable ASCII characters; 'flatcal_850 nm (1545458681-1545458781)\n 950 nm (1545458797-1545458897)\n 1100 nm (1545459125-1545459225)\n 1250 nm (1545460158-1545460258)\n 1375 nm (1545459879-1545459979).h5' contains characters not representable in ASCII or non-printable characters.
`

**Comment by baileyji** [comment]
Fixed.
