### ISSUE TITLE
Comments are not accepted

### ISSUE THREAD

**Issue by IsabelLipartito** [MazinLab/MKIDPipeline#34]
File "/opt/anaconda3/envs/pipeline/lib/python3.6/site-packages/astropy/io/fits/card.py", line 311, in value
raise ValueError('Illegal value: {!r}.'.format(value))
ValueError: Illegal value: ['Trapezium, a star system'].

This does not appear to be an issue with the length of the comment

**Comment by IsabelLipartito** [comment]
- !wc
  name: wavecal_01122019
  data:
    - !ob
      name: 850 nm
      start: 1547376554
      duration: 100  
      ndensity: open
      lamp: 100
    - !ob
      name: 950 nm
      start: 1547376662
      duration: 100
      ndensity: open
      lamp: 100
    - !ob
      name: 1100 nm
      start: 1547376788
      duration: 100
      ndensity: 1.0
      lamp: 40
    - !ob
      name: 1250 nm
      start: 1547376895
      duration: 100
      ndensity: 1.0
      lamp: 40
    - !ob
      name: 1375 nm
      start: 1547377000
      duration: 100      
      ndensity: 1.0
      lamp: 40

- !fc
  name: flatcal_01122019
  wavecal: wavecal_01122019

- !sob
  name: HD37021
  start: 1547374444
  duration: 100
  ra: 05:35:16.112
  dec: -05:23:06.89
  airmass: 1.261
  az: 48.7
  el: 52.5
  ha: 1.46
  parallactic: 45.2
  target: HD37021
  filter: Y Band, Filter Open
  observatory: subaru
  utc: 20190113101404
  instrument: mec
  dither_pos: 5
  wavecal: wavecal_01122019
  flatcal: flatcal_01122019
  wcscal: wcscal_01122019
  comments:
    - Trapezium, a star system

- !wcscal
  name: wcscal_01122019
  platescale: 0.1
  dither_ref: [0.23, -0.38]
  dither_home: [107, 61]
  device_orientation: -48

**Comment by baileyji** [comment]
@IsabelLipartito You'll need to edit your comment so that you preserve the raw formatting. See [this](https://guides.github.com/features/mastering-markdown/)

**Comment by IsabelLipartito** [comment]
I sent the yml as a gist instead, is that ok?

**Comment by baileyji** [comment]
Where is this getting added to the fits? I need more of the stack trace. The bug ins't actually in astropy.
