### ISSUE TITLE
Pipeline hangs after applying flatcals

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDPipeline#37]
After the apply_flatcal step, I've been noticing that the pipeline will just sit and not progress to hot pixel masking or generating the outputs (if hot pixel masking is commented out). Stopping the pipeline and commenting out the apply_flatcal step will cause it to progress to generating outputs with no issues.

**Comment by baileyji** [comment]
@steigersg Is this still an issue?

**Comment by steigersg** [comment]
just checked and this isn't an issue after flatcals but during hot pixel masking now its been just getting stuck and not completing - I had to comment out hp masking to get it to run through

**Comment by baileyji** [comment]
What happens with ncpu=1 and pausing the interpreter when it is hung?

**Comment by steigersg** [comment]
it's stuck in multiprocessing_logging.py ( I don't know how helpful that is) - specifically here

            try:
                record = self.queue.get(timeout=0.2)

where self is <MultiProcessingHandler (DEBUG)>
