### ISSUE TITLE
bug beginning in line 62 of run_pipeline

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDPipeline#38]
It seems like in the header there is some problem with creating nested metadata. Specifically, it seems like in the metadata there is somehow a key called "mkidpipeline" where the value associated with that key is a dictionary containing all the rest of the metadata. 

The actual error is 

  _File "/opt/anaconda3/envs/pipeline/lib/python3.6/site-packages/astropy/io/fits/card.py", line 507, in image
    self._image = self._format_image()
  File "/opt/anaconda3/envs/pipeline/lib/python3.6/site-packages/astropy/io/fits/card.py", line 966, in _format_image
    'too long'.format(self.keyword))
ValueError: The header keyword 'mkidpipeline' with its value is too long_

because the keyword is 'HIERARCH mkidpipeline ' with the respective value

"'{''batch_apply_metadata'': {''target'': ''HD1160'', ''observatory'': ''Subaru'', ''instrument'': ''MEC'', ''ra'': 3.9888, ''dec'': 4.2511, ''comments'': [''Star with a known Hot Jupiter''], ''dither_pos'': [-0.1, -0.75], ''name'': ''HD1160_dither_(HD1160_1545540554_dither.log)_0'', ''wavecal'': ''2018-12-23 051888891e1e27c48f09da56342a914aed89.npz'', ''flatcal'': ''flatcal_2018-12-23 051888891e1e27c48f09da56342a914aed89.npz.h5'', ''platescale'': 0.1, ''dither_ref'': [0.0, 0.0], ''dither_home'': [76, 123], ''device_orientation'': -48}}'"

**Comment by baileyji** [comment]
fixed.
