### ISSUE TITLE
wcs warning in drizzler that I suspect is leading to us to not see any photons in the output fits files 

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDPipeline#41]
WARNING: FITSFixedWarning: The WCS transformation has more axes (2) than the image it is associated with (0) [astropy.wcs.wcs]

The warning comes right after fetching the photons in the first fits file

**Comment by baileyji** [comment]
@RupertDodkins Where do we stand with this?

**Comment by RupertDodkins** [comment]
Looking into it
