### ISSUE TITLE
Bug in line 405 of drizzler when calling for a temporally drizzled image 

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDPipeline#49]
File "/home/steigersg/src/mkidpipeline/mkidpipeline/imaging/drizzler.py", line 406, in __init__
    self.ntimebins = int(inttime / self.exp_timestep)
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'

looks like in the TemporalDrizzler class, 'exp_time' is set to 0.1 if there isn't one specified, but in the form function (line 746) it is set to be 'None' which is causing the type error

**Comment by baileyji** [comment]
@RupertDodkins this looks like an emergent bug as a result of all the various switches you have added for command line testing as keyword arguments not being fully propagated and integrated into the drizzler params. Might be a good idea to standardize all your interfaces and either merge these things into the drizzle settings object or at least centralize parsing and evaluating. Any defaults that affect the execution of the algorithm MUST be broken out into the yml config and documented there. 

@steigersg I think a quick hack of changing the 'None' to .1 so you can keep testing is ok.

**Comment by baileyji** [comment]
Lets leave this open as a tag until we review all this together when we are both back.

**Comment by RupertDodkins** [comment]
Good shout
