### ISSUE TITLE
Drizzler bug when trying to get a "stack" output (line 618) 

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDPipeline#50]
File "/home/steigersg/src/mkidpipeline/mkidpipeline/imaging/drizzler.py", line 801, in form
    drizzle = DrizzledData(driz, mode, drizzle_params=drizzle_params)
  File "/home/steigersg/src/mkidpipeline/mkidpipeline/imaging/drizzler.py", line 618, in __init__
    self.variance = driz.variance
AttributeError: 'SpatialDrizzler' object has no attribute 'variance'

Line 618 of drizzler, but the problem starts on line 795 when calling "SpatialDrizzler" since SpatialDrizzler has no variance attribute

**Comment by steigersg** [comment]
don't get this bug when a "spatial" output is requested in the out.yml

**Comment by baileyji** [comment]
@RupertDodkins any chance you have some unpushed code on your laptop?
