### ISSUE TITLE
bug in drizzled.writefits() line of run_pipeline.py

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDPipeline#53]
It seems like if you specify an output path in your pipe.yml, drizzler will try to save its output not as a new file in the specified folder, but try to overwrite the contents of that folder leading to an error like the following 

  File "/opt/anaconda3/envs/pipeline/lib/python3.6/site-packages/astropy/io/fits/file.py", line 520, in _open_filename
    self._overwrite_existing(overwrite, None, True)
  File "/opt/anaconda3/envs/pipeline/lib/python3.6/site-packages/astropy/io/fits/file.py", line 412, in _overwrite_existing
    os.remove(self.name)
IsADirectoryError: [Errno 21] Is a directory: '/scratch/steiger/MEC/HD1160/'

where that path is the path I specified my outputs going to in the out.yml.

**Comment by RupertDodkins** [comment]
The filename parameter has to be set in out.yml (with '.fits' at the end) and the out parameter has to be set in pipe.yml. Can you tell me what you're using for these two variables so I can reproduce the error? If I set filename to nothing I get that error but is that not the behaviour we want?

**Comment by steigersg** [comment]
Okay, I didn't have the 'filename' parameter specified in my out.yml which led to that error so thats my bad. Maybe if thats not specified we should have an error message saying to do so? I just wasn't aware that was something I needed to have in there

**Comment by RupertDodkins** [comment]
Okay nice. I added an assertion
