### ISSUE TITLE
I think multiprocessing chokes on making h5 files if there are too many photons 

### ISSUE THREAD

**Issue by steigersg** [MazinLab/MKIDPipeline#54]
I'm trying to run the pipeline on the 1100 nm laser dither and I needed to reduce the ncpus to 1 in order to complete making the h5 files - otherwise the pipeline will be able to extract the data from the bin files but not populate the tables. 

I'm in the process of running it on 1 cpu now and it seems fine, just slow. I think this issue is being caused by the large amount of photons in these images since this laser dither is obviously much brighter than any astronomical source we'd look at. That's really the only difference that I can pinpoint at least between these files and any other files that have been pushed through the pipeline. 

If this is just something we have to live with then I may suggest a step in the pipeline that looks at how big the files are going to be and suggests to the user to not use multiprocessing

**Comment by baileyji** [comment]
Give a look at top. There is absolutely a limit, principally related to ram utilization. I don't think I ever saw a case where you couldn't get away with running 2-3 simultaneously, and I think generally 5 was safe. I've you can figure out a photons to peak ram relation I'll code up a rate limiter.

**Comment by steigersg** [comment]
I'm not sure if you're talking about a different thing, but in line 33 of mkidbin.pyx there is already a relation that someone(?) found between number of photons and space in memory

**Comment by baileyji** [comment]
Right, I did that. ok. I’ll look at this in a bit. Can you confrim that the stalls you were seeing don’t happen with ncpu =2-3 (or some number >1 but not saturating ram)? I’m not sure how much effort adding a predictive gate in a solid manner will be.

-Jeb
 
—— 
Dr. J.I. Bailey, III (Jeb) / Project Scientist
Mazin Lab / Department of Physics, UCSB
jebbailey.com <http://jebbailey.com/> / +1 (734) 389-5143 / skype:spacecolonyone <skype:spacecolonyone>

**Comment by steigersg** [comment]
ncpu = 3 had no issues
