### ISSUE TITLE
Wavecal is only being run on beam-mapped pixels. It should run on all of them.

### ISSUE THREAD

**Issue by zobristnicholas** [MazinLab/MKIDPipeline#58]
Currently, the wavecal code will only run on pixels that have a good beam-map flag. This was not the intended behavior since there is no reason to throw out those pixels at that stage of analysis.

This is enforced in bin2hdf where pixels with bad beam-map flags are not included in the h5 file---specifically in binprocessor.c ParseToMem() where the mapflag variable is hardcoded to always be 1. 

We should expose that flag to python as a config option that can be set to give all the data to the wavecal if needed.

**Comment by baileyji** [comment]
@nswimmer @steigersg Is this still an issue?
