### ISSUE TITLE
Bin2HDF - add error handling to config/beammap parsing 

### ISSUE THREAD

**Issue by neelay893** [MazinLab/MKIDPipeline#7]
Bin2HDF segfaults when provided a beammap that does not match the provided array dimensions. It should be able to detect this and exit w/ a meaningful error.

**Comment by baileyji** [comment]
Need to add non-zero exit to bin2hdf based on mismatch between array dimensions in the config file and in the beammap file. Need check to ensure that maxx & maxy in beammap is <= nrows and ncols in config file, if not exit with prejudice.
