### ISSUE TITLE
Speccal has rounding errors that lead to speccal not being applied after calculation

### ISSUE THREAD

**Issue by nswimmer** [MazinLab/MKIDPipeline#74]
In the spectral calibration step, the wvl_bin_center values are calculated from the wvl_bin_edges. When saved to the soln_file, those bin center values have been 'off' by a very small number, but when applying the spectral cube to get a flux calibrated spectral cube (in the apply function) there is a `soln_wvl_bin_centers==wvl_bin_centers` comparison. Because there is a slight difference in these values (e.g. 10349.999999998 to 10350), that causes this comparison to fail and does not apply the spectral calibration to the desired data.

**Comment by baileyji** [comment]
File/line/git commit?

**Comment by nswimmer** [comment]
speccal.py, function `apply()` (line 675 in my copy).
The line in question is 
`    if np.all(soln_wvl_centers == wvl_bin_centers):
        for wvl, cube in enumerate(s_cube):
            flux_calibrated_cube[wvl] = s_cube[wvl] * curve(wvl_bin_centers[wvl])`
