### ISSUE TITLE
Cosmiccal Breaks When Updating h5 Header

### ISSUE THREAD

**Issue by nswimmer** [MazinLab/MKIDPipeline#83]
For reference, `cc.obs = '/work/nswimmer/20211210/out/1639185925.h5'` in the first block and `obs = '/work/nswimmer/20211210/out/1639185925.h5'` in the second. This code is being run on the same file.

In cosmiccal.py, when the following block is run
```
    md = {'region': [50, 100], 'thresh': 0.0, 'method': 'poisson', 'wavecut': [800, 1310]}

    cc.obs.enablewrite()
    for k, v in md.items():
        cc.obs.update_header(f'cosmiccal.{k}', v)

    cc.obs.attach_new_table('cosmics', 'Cosmic Ray Info', 'impacts', CRImpact, "Cosmic-Ray Hits", impacts)
    cc.obs.update_header(f'cosmiccal', True)
    cc.obs.disablewrite()
    getLogger(__name__).info(f'Cosmiccal applied to {o.name}')
```
this error shows up
```
2022-01-26 12:39:18 mkidpipeline.pipeline       :CRITICAL (wrapper_decorator:55[pid=1192510]) Caught exception during run of mkidpipeline.steps.cosmiccal.apply
Traceback (most recent call last):
  File "/home/nswimmer/src/mkidpipeline/mkidpipeline/pipeline.py", line 52, in wrapper_decorator
    return func(*args, **kwargs)
  File "/home/nswimmer/src/mkidpipeline/mkidpipeline/steps/cosmiccal.py", line 205, in apply
    cc.obs.update_header(f'cosmiccal.{k}', v)
  File "/home/nswimmer/src/mkidpipeline/mkidpipeline/photontable.py", line 1048, in update_header
    setattr(self.file.root.photons.photontable.attrs, key, value)
  File "/home/nswimmer/.conda/envs/pipeline/lib/python3.7/site-packages/tables/attributeset.py", line 483, in __setattr__
    self._g__setattr(name, value)
  File "/home/nswimmer/.conda/envs/pipeline/lib/python3.7/site-packages/tables/attributeset.py", line 425, in _g__setattr
    self._g_setattr(self._v_node, name, stvalue)
  File "tables/hdf5extension.pyx", line 713, in tables.hdf5extension.AttributeSet._g_setattr
  File "/home/nswimmer/.conda/envs/pipeline/lib/python3.7/copyreg.py", line 73, in _reduce_ex
    "defining __getstate__ cannot be pickled") from None
TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled
Traceback (most recent call last):
  File "/home/nswimmer/src/mkidpipeline/mkidpipeline/pipeline.py", line 52, in wrapper_decorator
    return func(*args, **kwargs)
  File "/home/nswimmer/src/mkidpipeline/mkidpipeline/steps/cosmiccal.py", line 205, in apply
    cc.obs.update_header(f'cosmiccal.{k}', v)
  File "/home/nswimmer/src/mkidpipeline/mkidpipeline/photontable.py", line 1048, in update_header
    setattr(self.file.root.photons.photontable.attrs, key, value)
  File "/home/nswimmer/.conda/envs/pipeline/lib/python3.7/site-packages/tables/attributeset.py", line 483, in __setattr__
    self._g__setattr(name, value)
  File "/home/nswimmer/.conda/envs/pipeline/lib/python3.7/site-packages/tables/attributeset.py", line 425, in _g__setattr
    self._g_setattr(self._v_node, name, stvalue)
  File "tables/hdf5extension.pyx", line 713, in tables.hdf5extension.AttributeSet._g_setattr
  File "/home/nswimmer/.conda/envs/pipeline/lib/python3.7/copyreg.py", line 73, in _reduce_ex
    "defining __getstate__ cannot be pickled") from None
TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled
```

However, if we run this block of code mimicking what cosmiccal.py is doing to the header
```
from mkidpipeline.photontable import Photontable as pt

obs = pt('/work/nswimmer/20211210/out/1639185925.h5')
md = {'region': [50, 100], 'thresh': 0.0, 'method': 'poisson', 'wavecut': [800, 1310]}

obs.enablewrite()
for k, v in md.items():
    obs.update_header(f'cosmiccal.{k}', v)

obs.update_header(f'cosmiccal', True)
obs.disablewrite()
```

There is no error, the header is updated appropriately, and the code completes successfully.

**Comment by baileyji** [comment]
I believe every call of `cc.obs` returns a unique `Photontable`, so the first code snippet would be inherently destined to fail as each call is on a successive object and never on an object opened in write mode. 

Your second snippet works because the operations are all done on the same object.

**Comment by nswimmer** [comment]
I'm not sure how to fix this, I tried `obs = cc.obs` then switching every version of `cc.obs` to `obs`, I tried writing a function that has the photontable passed to it as a parameter and it still errors out. Happy to keep playing with this but I'm not sure how else to go about it.

**Comment by baileyji** [comment]
Based on the snippets above I'm strggling to see why
```
obs = pt('/work/nswimmer/20211210/out/1639185925.h5')
md = {'region': [50, 100], 'thresh': 0.0, 'method': 'poisson', 'wavecut': [800, 1310]}

obs.enablewrite()
for k, v in md.items():
    obs.update_header(f'cosmiccal.{k}', v)

obs.update_header(f'cosmiccal', True)
obs.disablewrite()
```
would work

but 
```
    md = {'region': [50, 100], 'thresh': 0.0, 'method': 'poisson', 'wavecut': [800, 1310]}

    #cc.obs.enablewrite()
    obs = cc.obs
    obs.enablewrite()
    for k, v in md.items():
        obs.update_header(f'cosmiccal.{k}', v)

    #obs.attach_new_table('cosmics', 'Cosmic Ray Info', 'impacts', CRImpact, "Cosmic-Ray Hits", impacts)
    obs.update_header(f'cosmiccal', True)
    obs.disablewrite()
```

would not. Here I've commented out `attach_new_table` for clarity as from the issue I gather the TypeError is raised in the for loop. 

Another possibility is `cc.obs` was instantiated in an odd way. I've been assuming it was instantiated at some earlier point via cc.obs = Photontable(somefile)

**Comment by nswimmer** [comment]
That's correct, the TypeError is raised during the first iteration of the for loop every time (even if the order of `md` is switched around).

As far as the instantiation, and h5 from the dataset is passed to the class init
```
    cc = CosmicCleaner(o.h5, **methodkw)
```
And in the init function we have
```
    def __init__(self, file, wavecut=None, method="poisson", region=(50, 100), bin_size=10):
        self.obs = Photontable(file)
```

I'm not sure if that classifies as being instantiated a certain way.

**Comment by baileyji** [comment]
That is identical to your test case that worked (assuming `pt` is the `Photontable` class). Short of something with multiproccessing (try running with 1 cpu if you aren't) I'm left to infer that your manually defined `md` is not actually consistent with the metadata dict in the step.

**Comment by nswimmer** [comment]
Yes, the import statement is
```from mkidpipeline.photontable import Photontable as pt```

I've been running with 1 cpu the whole time (`ncpu:1` everywhere it appears in the pipe.yaml).

`md` is made _slightly_ differently between the two: in my debugging code I have
```
    md = {'region': [50, 100], 'thresh': 0.0, 'method': 'poisson', 'wavecut': [800, 1310]}
```
compared to
```
    md = dict(region=cc.removal_range, thresh=cc.threshold, method=cc.method, wavecut=cc.wave_range)
```

But within that I've type checked each of the values of the dict and they are the same.
With that said, I replaced the `md={'key1':value1, ...}` with the `md=dict(key1=value1, ...)` construction in my debugging code and it works. It's also robust to changing the types within reason (e.g. it works whether [50,100] is a list or a tuple, 0.0 is a float or an int, etc.)

**Comment by nswimmer** [comment]
Closed with https://github.com/MazinLab/MKIDPipeline/commit/ee24e3de3cc1004525799c8f3663b4a5d89e0509
