### ISSUE TITLE
ADI Bug 1: Metadata not being grabbed properly in drizzler

### ISSUE THREAD

**Issue by nswimmer** [MazinLab/MKIDPipeline#84]
When creating a drizzled output that uses `adi_mode: true`, if you do not specify the object name in the `header:` section of the `!MKIDDither` block in the data.yaml, the Drizzler will try to get the object name (and RA/DEC/other metadata) by grabbing that metadata from each photontable that is part of the dither. This occurs in `mp_worker()` (drizzler.py line 532) specifically in line 562 when the call `wcs = pt.get_wcs(...)` is made.

In the `get_wcs()` function (when in ADI mode) a `single_pa_time` is passed as a kwarg to this function. Thie `single_pa_time` is equal to the timestamp from the first second of the first dither step. However, in lines 734-45 of photontable.py
```
        try:
            for t in sample_times:
                md = self.metadata(t)
                head = mkidcore.metadata.build_header(md, unknown_keys='ignore')
                ref_pixels.append(compute_wcs_ref_pixel((md['E_CONEXX'], md['E_CONEXY']),
                                                        reference_pixel=(head['E_PREFX'], head['E_PREFY']),
                                                        reference=(head['E_CXREFX'], head['E_CXREFY']),
                                                        conex_deltas=(md['E_DPDCX'], md['E_DPDCY'])))
        except KeyError:
            getLogger(__name__).warning('Insufficient data to build a WCS solution, conex info missing')
            return None
```
when a photontable does not contain data from that first timestamp (i.e. it is a photontable for the 2nd dither dwell step or later), the object name, RA, DEC, and other necessary metadata is not grabbed by the `self.metadata()` call and the `header` populates those keys with the value `'UNKNOWN'`.  This then results in the error that there is insufficient data to build a WCS solution and Drizzler errors out.

**Comment by baileyji** [comment]
Interesting. It seems like there may be several issues here.
1. Drizzler (and all of the things it uses) should not be getting any metadata from the definition, all of that should have been associated with the photontable and be pulled from the file.
2. Do the subsequent steps have good metadata, just at subsequent timesteps? My guess is that they do and so the query in ADI mode needs to be refined so that it isn't making an implicit assumption that the PA time is the same as the time for the metadata. We should take later today after I've thought and looked at code.

**Comment by nswimmer** [comment]
1) I think in previous cases (non-ADI) this probably was okay since you're ostensibly using metadata from within the associated photontable, but yeah when you're trying to grab something that falls outside of that range it gets all mucked up.

2) I'm not sure specifically what you're referring to here. In the case when it pulls no metadata, no, because drizzler errors out, as it can't create any WCS solutions. In the case where an object name is included in the data definition header, it is certainly able to continue, as it gets the object name from that header and then RA/DEC from simbad, but its doesn't properly grab telescope metadata

**Comment by nswimmer** [comment]
Which might be related to why #85 is happening

**Comment by baileyji** [comment]
I don't understand your comment on 1. I am saying that after attaching metadata no step in the pipeline should be accessing information about an observation from a definition attribute and rather it should come from pt.metadata (or possibly some other tables metadata in a collection of tables). While we might need some way to override this, if so, it needs to be explicit, and and loudly logged.

As for two, my question is "Do the tables of subsequent dither steps have metadata for their time window?" the truth of this isn't affected by steps.drizzler. On a related note when drizzler is querying `Photontable.get_wcs` with `wcs_times` (~l. 561) are any/all query times within the file?
