### ISSUE TITLE
Project is missing mkidcore dependency

### ISSUE THREAD

**Issue by ld-cd** [MazinLab/MKIDPipeline#87]
this is needed to import `Photontable`

**Comment by ld-cd** [comment]
This does not work with the current develop version of mkidcore, see [here](https://github.com/MazinLab/MKIDCore/issues/4)

**Comment by baileyji** [comment]
Probably should be using the "xkid" branch.

**Comment by ld-cd** [comment]
If the current default branch is not importable then the xkid branch should be merged to `develop`, or the default branch changed to `xkid`

**Comment by ld-cd** [comment]
Resolved by https://github.com/MazinLab/MKIDPipeline/commit/763188cc35e472c533c0011b44cf8387c3a7aca9
