### ISSUE TITLE
This key no longer exists

### ISSUE THREAD

**Issue by ld-cd** [MazinLab/MKIDPipeline#88]
https://github.com/MazinLab/MKIDPipeline/blob/f4ad012c574e0ef5718706e6712b5c743eb3e697/mkidpipeline/photontable.py#L16

Should there be a DEFAULT_KEY_INFO [here](https://github.com/MazinLab/MKIDCore/blob/develop/mkidcore/metadata.py#L171)?

**Comment by baileyji** [comment]
I suspect this is a result of working with a stale branch.

**Comment by ld-cd** [comment]
This is the develop branch on both repos as are all of the issues I filled

**Comment by ld-cd** [comment]
Potentially resolved by https://github.com/MazinLab/MKIDPipeline/commit/763188cc35e472c533c0011b44cf8387c3a7aca9 further testing needed

**Comment by ld-cd** [comment]
Resolved by 763188cc35e472c533c0011b44cf8387c3a7aca9
