### ISSUE TITLE
Edit setup.py so that bin2hdf gets installed onto the path as part of the repository.

### ISSUE THREAD

**Issue by baileyji** [MazinLab/MKIDPipeline#9]
See e.g. https://stackoverflow.com/questions/33168482/compiling-installing-c-executable-using-pythons-setuptools-setup-py. May require a simple makefile.

**Comment by IsabelLipartito** [comment]
Here's how it can be done for now:

In the mkidpipeline/hdf directory run this command:
/usr/local/hdf5/bin/h5cc -shlib -pthread -g -o bin2hdf bin2hdf.c

Edit your .bashrc file to add this to your path
export PATH=/home/isabel/src/mkidpipeline/mkidpipeline/hdf/:$PATH

source activate .bashrc
