### ISSUE TITLE
Python 3.10 Compatibility

### ISSUE THREAD

**Issue by nzivkov** [MazinLab/MKIDPipeline#92]
Suspected that the following packages and/or the way they're implemented are preventing the pipeline environment from working in 3.10: 
  - conda-forge/linux-64::coverage==6.5.0=py37h540881e_0
  - conda-forge/noarch::importlib_metadata==4.11.4=hd8ed1ab_0
  - conda-forge/noarch::jsonschema==4.17.3=pyhd8ed1ab_0
  - conda-forge/linux-64::pluggy==1.0.0=py37h89c1867_3
  - conda-forge/linux-64::keyring==23.9.3=py37h89c1867_0
  - conda-forge/linux-64::pytest==7.2.0=py37h89c1867_0
  - conda-forge/noarch::asdf==2.11.0=pyhd8ed1ab_0
  - conda-forge/noarch::pytest-arraydiff==0.3=py_0
  - conda-forge/noarch::pytest-astropy-header==0.1.2=py_0
  - conda-forge/noarch::pytest-cov==4.0.0=pyhd8ed1ab_0
  - conda-forge/noarch::pytest-doctestplus==0.12.1=pyhd8ed1ab_0
  - conda-forge/noarch::pytest-filter-subpackage==0.1.1=py_0
  - conda-forge/noarch::pytest-mock==3.10.0=pyhd8ed1ab_0
  - conda-forge/noarch::pytest-openfiles==0.5.0=py_0
  - conda-forge/noarch::pytest-remotedata==0.4.0=pyhd8ed1ab_0
  - conda-forge/noarch::gwcs==0.17.1=pyhd8ed1ab_0
  - conda-forge/noarch::pytest-astropy==0.10.0=pyhd8ed1ab_0
  - conda-forge/noarch::astroquery==0.4.6=pyhd8ed1ab_0
  - conda-forge/noarch::ndcube==2.0.3=pyhd8ed1ab_0
  - conda-forge/linux-64::photutils==1.3.0=py37h5e8e339_1
  - conda-forge/linux-64::regions==0.5=py37h5e8e339_1
  - conda-forge/noarch::specutils==1.9.1=pyhd8ed1ab_0
  - pypi/pypi::nbformat==5.8.0=pypi_0
  - pypi/pypi::pdm==2.10.4=pypi_0
  - pypi/pypi::notebook-shim==0.2.2=pypi_0
  - pypi/pypi::jupyter==1.0.0=pypi_0
  - pypi/pypi::nbconvert==7.3.1=pypi_0
  - pypi/pypi::nbclient==0.7.3=pypi_0
  - pypi/pypi::virtualenv==20.26.3=pypi_0
  - pypi/pypi::nbclassic==0.5.5=pypi_0
  - pypi/pypi::notebook==6.5.4=pypi_0
  - pypi/pypi::jupyter-server==1.23.6=pypi_0

**Comment by ld-cd** [comment]
Resolved by https://github.com/MazinLab/MKIDPipeline/commit/763188cc35e472c533c0011b44cf8387c3a7aca9 runs in python3.9-3.12
